### PR TITLE
Build properties update acs

### PR DESCRIPTION
**Pull request by YuriyShestakov**
1. There were errors in acs-aem-commons-content packages' urls.
2. ACS versions updated to latest.

### CODE REVIEW

**Comment by kapilmalik84** [comment]
Running ANT target: download_all
      Downloading latest AEM hotfix packages from PackageShare
      Connecting to Adobe Package Share with ID: MYADOBEID_REPLACED
      Download in progress, please wait until it is complete
Sorry, this target couldn't be completed properly
The error message is:
The following error occurred while executing this line:
C:\AEM\aem-demo-machine-master\build.xml:2184: The following error occurred while executing this line:
C:\AEM\aem-demo-machine-master\build.xml:1862: The following error occurred while executing this line:
C:\AEM\aem-demo-machine-master\build.xml:1870: The following error occurred while executing this line:
C:\AEM\aem-demo-machine-master\build.xml:1922: There was a problem downloading a package from PackageShare. Please verify the download properties /content/companies/private/day/packages/adobe/cq610/hotfix/cq-6.1.0-hotfix-11724.
------------------------------------
Second error is for Hotfix download:
Running ANT target: download_hotfixes_packages
      Downloading latest AEM hotfix packages from PackageShare
      Connecting to Adobe Package Share with ID: MYADOBEID_REPLACED
      Download in progress, please wait until it is complete
Sorry, this target couldn't be completed properly
The error message is:
The following error occurred while executing this line:
C:\AEM\aem-demo-machine-master\build.xml:1862: The following error occurred while executing this line:
C:\AEM\aem-demo-machine-master\build.xml:1870: The following error occurred while executing this line:
C:\AEM\aem-demo-machine-master\build.xml:1922: There was a problem downloading a package from PackageShare. Please verify the download properties /content/companies/private/day/packages/adobe/cq610/hotfix/cq-6.1.0-hotfix-11724.

**Comment by coatpont** [comment]
can you please retry? I just tried download_all and this particular hotfix was downloaded properly.

**Comment by kapilmalik84** [comment]
let me pull the changes done in last week and then try again.

**Comment by kapilmalik84** [comment]
I Am using AEM 6.2 jar and License and this (cq-6.1.0-hotfix-11724) hotfix is for AEM 6.1
Is it right?

**Comment by kapilmalik84** [comment]
I am using the AEM 6.2 Jar and license however this hot fix(cq-6.1.0-hotfix-11724) is for AEM 6.1.
is this the right behavior?

**Comment by coatpont** [comment]
yes, hotfixes are downloaded always for 6.1, 6.2 and 6.3 independently from the version of AEM you are using

**Comment by kapilmalik84** [comment]
Hi coatpont,
I tried again and i am getting the following error:
Running ANT target: download_all
      Downloading latest AEM hotfix packages from PackageShare
      Connecting to Adobe Package Share with ID: kapil.malik@mycompany.com
      Download in progress, please wait until it is complete
Sorry, this target couldn't be completed properly
The error message is:
The following error occurred while executing this line:
C:\AEM\HM-Demo\build.xml:2184: The following error occurred while executing this line:
C:\AEM\HM-Demo\build.xml:1862: The following error occurred while executing this line:
C:\AEM\HM-Demo\build.xml:1870: The following error occurred while executing this line:
C:\AEM\HM-Demo\build.xml:1922: There was a problem downloading a package from PackageShare. Please verify the download properties /content/companies/private/day/packages/adobe/cq610/hotfix/cq-6.1.0-hotfix-11724.

**Comment by coatpont** [comment]
can you see this package while logging manually in PackageShare at https://www.adobeaemcloud.com/content/clouds/en/packages.html ?

I wonder if it's "internal" nature is getting in the way of being downloaded for non-Adobe users

**Comment by kapilmalik84** [comment]
yes it looks like i cant see this from packageshare.
packageshare

**Comment by coatpont** [comment]
ok thanks - then I'll have to handle this use case in the download logic - a fix will be coming soon, in the meantime you can simply remove the properties from build.properties

**Comment by kapilmalik84** [comment]
Hi Coatpont,
i tried removing the packages from build.properties and found another package which is not available publicly. here is the list:
1. cq-6.1.0-hotfix-11724
2. cq-6.1.0-hotfix-8124
Please help by providing the same using google drive or any other setup we are using in the project.

**Comment by YuriyShestakov** [comment]
@kapilmalik84 @coatpont 
All private/day/packages are not available outside adobe vpn, and only available with special login/password which you have to specify in build properties. So, download_all doesn't work for common users.
I've totally deleted these packages in my branch, and can use Demo machine only that way.

**Comment by coatpont** [comment]
I just pushed a change that results in non-visible files to be ignored (with warning), allowing for the build to proceed anyway, https://github.com/Adobe-Marketing-Cloud/aem-demo-machine/commit/2b5e242c93ae5aa9a2117216b822920c37d25dcc

**Pull request merged**
